extends: airbnb-base
rules:
  "object-curly-spacing": 0
  "comma-dangle": 0
  "one-var": 0
  "indent": ["error", 2, { "VariableDeclarator": 3 }]
  "arrow-body-style": 0
  "block-spacing": 0
  "no-underscore-dangle": 0
  "no-unused-expressions": 0
  "no-param-reassign": 0
  "no-plusplus": 0
  "no-use-before-define": 0
  "import/no-extraneous-dependencies": ["error", {"devDependencies": true}]