dbUrl: mongodb://localhost:27017/dev
host: https://www.massivemusicquiz.com
routes:
  login: /api/signins
  play: /game/facile
  logout: /logout
socketUrl: https://sso.massivemusicquiz.com:4342
gameId : facile
user:
  email: gurumatazz@yopmail.com
  password: aa
connect: true
answer: true